### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by moliya** [YPLiang19/Mango#13]
- 是否可以支持static、const修饰符
- dispatch_after、dispatch_once两个常用方法无法使用
- 为对象添加属性时，如果属性是基本类型的话会无法赋值，比如下面的代码
```objc
class SuperMyController:UIViewController{
@property (assign, nonatomic) int count;
- (void)viewDidLoad {
    super.viewDidLoad();

    self.count = 12;
    NSLog(@"count=" + self.count); //输出 count=0
}
```

**Comment by YPLiang19** [comment]
@moliya 由于C语言 static变量时在编译器处理的，所以MangoFix无法支持static变量，所以dispatch_once也无法支持，你可以通过其他方式实现该类似功能。dispatch_after和基本属性值丢失的问题，会在下一个版本修复。基本上属性值丢失问题，你现在可以把修饰符改为strong即可。对于dispatch_after你现在可以在MangoFix执行上下文中注入这个全局函数，如下代码

```
self.context[@"dispatch_after"] = [MFValue valueInstanceWithBlock:^(dispatch_time_t when, dispatch_queue_t  _Nonnull queue, dispatch_block_t block){
        dispatch_after(when, queue, block);
    }];
```
调用代码如下：
```
- (void)testGCDAfterWithCompletionBlock:(Block)completion{
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 3 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        completion(@"success");
    });
}
```
需要注意的是MangoFix不支持手动类型强转，所以3 * NSEC_PER_SEC不要手动转(int64_t)(3 * NSEC_PER_SEC)，MangoFix会在运行时自动转换。
