### ISSUE TITLE
block属性变量赋值导致内存泄漏

### ISSUE THREAD

**Issue by Aaronlianggq** [YPLiang19/Mango#15]
场景：native存在block类型的属性，在hotfix里面如果此block赋值则会导致泄漏

如列子
//native 声明的属性
@property(nonatomic , copy) void(^testBlock)(void);

//hotfix
{
          //此代码运行后 当前对象会内存泄漏
           self.testBlock = ^ {
                NSLog(@"block go");
            };
}

**Comment by YPLiang19** [comment]
在1.1.7版本中已重写了block作用域链，以及block循环引用问题，已不存在这种问题，请下载最新版本。如果还有不太清除的请参考这篇文章（ https://www.jianshu.com/p/7ae91a2daead ）  中的第五点"如何解决Block循环引用问题"。
