### ISSUE TITLE
您好，信号量调用崩溃，在 add_gcd_build_in 没找到信号量相关的？是不支持吗 ？

### ISSUE THREAD

**Issue by zhaoxuezhi** [YPLiang19/Mango#17]
class HLJSearchConfigApi : HLJClientBaseRequest {

    - (void)requestSearchRecommond {
        dispatch_semaphore_signal(self.semaphore);
    }
}

**Comment by YPLiang19** [comment]
@zhaoxuezhi  可以通过MFContext的- (void)setObject:(MFValue *)value forKeyedSubscript:(NSObject <NSCopying> *)key; 动态扩展所需要的C函数。

**Comment by zhaoxuezhi** [comment]
您好：
1、如何在 demo.mg 中动态扩展 C 函数，例如我所提的问题，修复线上的信号量 bug ?
2、关于：在MangoFix中注入全局对象，没有get 到具体的使用场景，是要预先在 OC 代码中设置，还是在 demo.mg 中去添加 ?
关于以上，希望能有参考代码。非常感谢！！

**Comment by YPLiang19** [comment]
@zhaoxuezhi 将需要的C函数用block进行封装，然后将block注入到MangoFix作为全局变量，然后调用block。

**Comment by zhaoxuezhi** [comment]
@YPLiang19  根据您的提示发现有崩溃，以下为代码及崩溃信息截图，帮忙看下什么原因造成的 ？

class HLJSearchConfigApi : HLJClientBaseRequest {

    - (void)requestSearchRecommond {

        // 定义 block
        block semaphoreBlock = ^(dispatch_semaphore_t se){
            dispatch_semaphore_signal(se);
        };

        // 获取 MFContext 变量
        MFValue *value = MFValue.valueInstanceWithBlock:(semaphoreBlock);
        AppDelegate *delegate = UIApplication.sharedApplication.delegate;
        MFContext *context = delegate.mfContext;

        // 设置全局变量
        context.setObject:forKeyedSubscript:(value,@"dispatch_semaphore_signal");

        // 调用 block， semaphore 在类初始化时已初始化
        semaphoreBlock(self.semaphore);
    }
}
![20190524151114](https://user-images.githubusercontent.com/10152153/58309334-82d76a00-7e36-11e9-86ba-61dff608dd39.jpg)
![20190524150428](https://user-images.githubusercontent.com/10152153/58309358-984c9400-7e36-11e9-98e2-f68b6c1cebef.jpg)
![image](https://user-images.githubusercontent.com/10152153/58309503-05f8c000-7e37-11e9-8f01-84b965be1181.png)

**Comment by YPLiang19** [comment]
@zhaoxuezhi  预埋要在APP中预埋。

**Comment by zhaoxuezhi** [comment]
@YPLiang19 预埋是 OK 的。
有个疑问 `- (void)setObject:(MFValue *)value forKeyedSubscript:(NSObject *)key` 这个方法的设计初衷就是要在 APP 中执行的吗 ？  我在 demo.mg 中使用了该方法，设置和数据读取都是 ok 的， 推荐这样写吗 ？ 是否安全 ？

// 设置全局变量

class HLJNewSearchResultViewController : BaseViewController {

    - (void)beginNewSearch {

        //  获取  MFContext
        AppDelegate *delegate = UIApplication.sharedApplication.delegate;
        MFContext *context = delegate.mfContext;

        // 设置全局变量
        MFValue *value = MFValue.valueInstanceWithObject:(@"测试 MF 插入");
        context.setObject:forKeyedSubscript:(value,@"setTestValue");

        // 回调原方法  
        self.ORGbeginNewSearch();
    }
}
`
// 读取全局变量
class HLJProductDetailViewController : BaseViewController {

    - (void)viewDidLoad {

       //  获取  MFContext
        AppDelegate *delegate = UIApplication.sharedApplication.delegate;
        MFContext *context = delegate.mfContext;

       // 读取全局变量
        MFValue *value = context.objectForKeyedSubscript:(@"setTestValue");
        NSLog(@"value = " + value.objectValue + @"\n");

      // 回调原方法 
        self.ORGviewDidLoad();
    }
}

**Comment by YPLiang19** [comment]
在mg文件中可以使用，但是无法注入C函数

**Comment by zhaoxuezhi** [comment]
@YPLiang19 OK，非常感谢！！

**Comment by YPLiang19** [comment]
@zhaoxuezhi  建议升级到1.1.9， 1.1.9添加了大量的GCD API，其中就包括dispatch_semaphore相关的API

**Comment by zhaoxuezhi** [comment]
@YPLiang19 赞 ！
