### ISSUE TITLE
super.viewDidLoad()  不加括号会崩溃

### ISSUE THREAD

**Issue by zhaoxuezhi** [YPLiang19/Mango#18]
@YPLiang19 看文档里有写 OC 无参方法的调用可以省略后面的括号，但是`super.viewDidLoad`这种写法会崩溃，貌似死循环：

class SuperMyController:UIViewController{

- (void)viewDidLoad {
    super.viewDidLoad；
}

![image](https://user-images.githubusercontent.com/10152153/58679756-6e93ef80-8397-11e9-9e80-e0b0864fabbe.png)

![image](https://user-images.githubusercontent.com/10152153/58679840-bd418980-8397-11e9-87e7-6a7c2fcced3f.png)

**Comment by YPLiang19** [comment]
@zhaoxuezhi  对于super还不行，必须要加上();

**Comment by YPLiang19** [comment]
最新版本已经解决了这个问题，可以试试~

**Comment by YPLiang19** [comment]
@zhaoxuezhi 最新版本已经解决了这个问题，可以试试~
