### ISSUE TITLE
frame或者bounds为null

### ISSUE THREAD

**Issue by ThinkDifferents** [YPLiang19/Mango#29]
在方法中打印试图有frame,但是直接取试图的frame为null...

**Comment by YPLiang19** [comment]
NSLog打印的是对象，打印frame可以自己添加方法。

**Comment by ThinkDifferents** [comment]
好的，感谢回复，我试试


| |
ThinkDifferents
|
|
m18534353727@163.com
|
签名由网易邮箱大师定制


在2020年05月7日 14:02，雍鹏亮<notifications@github.com> 写道：

NSLog打印的是对象，打印frame可以自己添加方法。

**Comment by YPLiang19** [comment]
十分感谢🙏，已修复。
