### ISSUE TITLE
关于RSA加密的问题

### ISSUE THREAD

**Issue by pepsikirk** [YPLiang19/Mango#35]
我在升级到1.4的时候发现，MFContext 创建需要传的是私钥，而公钥用来加密，那就是需要把私钥保存到客户端本地，相当于公开，而公钥是私有的。
而据我所知，OpenSSL 生成的私钥是可以直接提取公钥的，客户端就可以同时获取到私钥和公钥，所以这样的加密是基本没有意义的。
而根据我的查询JSPatch 就是使用私钥加密MD5来保证安全性的，https://jspatch.com/Docs/security，也可以看看知乎相关讨论 https://www.zhihu.com/question/25912483
在我看来RSA的算法中私钥公钥其实一样，OpenSSL 区分为公钥私钥后才决定了私钥为什么要私有。所以客户端应该保存的是公钥，用来解密，而私钥是私有的用来加密。
感谢你开发的工具，确实很好用，希望能够完善这个安全问题，谢谢

**Comment by YPLiang19** [comment]
公钥顾名思义是就是所有人都可以获取的key，一般用来做签名校验，如果用公钥进行解密那所有的人都可以解密了。而私钥一般为私有，用来解密，即只有特定人才能解密。

**Comment by YPLiang19** [comment]
公钥顾名思义是就是所有人都可以获取的key，一般用来做签名校验，如果用公钥进行解密那所有的人都可以解密了，显然我们只希望我们自己的App来解密，而不希望其他获取到密文的人来解密。而私钥一般为私有，用来解密，即只有特定人才能解密。

**Comment by pepsikirk** [comment]
> 公钥顾名思义是就是所有人都可以获取的key，一般用来做签名校验，如果用公钥进行解密那所有的人都可以解密了，显然我们只希望我们自己的App来解密，而不希望其他获取到密文的人来解密。而私钥一般为私有，用来解密，即只有特定人才能解密。

目前正是使用公钥加密，那么公钥就是私有的，而将私钥放到客户端，这代表随便砸壳以后就可以获取到私钥，所以私钥才是真正公开的。
所以我才说需要使用私钥加密，而公钥放到客户端，用来解密。在这样的场景下，加密的作用是保证文件在传输过程中没有被篡改和伪造。

**Comment by YPLiang19** [comment]
RAS主要应用场景：
1. 加密和解密：公钥加密，私钥解密
2. 签名和验证：私钥签名，公钥验证
MangoFix客户端的角色为私钥解密。
