### ISSUE TITLE
子类的初始化方法中通过super调用父类的初始化方法，参数会变为nil，大家有遇到这个问题吗，或者应该怎么解决

### ISSUE THREAD

**Issue by itdongbaojun** [YPLiang19/Mango#39]
子类的初始化方法中通过super调用父类的初始化方法，参数会变为nil，大家有遇到这个问题吗，或者应该怎么解决

**Comment by itdongbaojun** [comment]
-(instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration *)configuration {
     ...
    self = [super initWithFrame:frame configuration: configuration];
    ...
   return self;
}

上述代码写成mango后
    self = super.initWithFrame:configuration:(frame,configuration);
是否存在问题？
通过super调用父类的方法后，会报Configuration为空
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Configuration cannot be nil'

上述问题该怎么解决呢？还是我哪里写的有问题？
@YPLiang19

**Comment by xzwgithub** [comment]
应该是脚本语言写的有问题，我也遇到过类似的初始化方法，参数为空

**Comment by YPLiang19** [comment]
十分感谢🙏，已修复。
