### ISSUE TITLE
大神，有个问题，请教下

### ISSUE THREAD

**Issue by chen751318834** [YPLiang19/Mango#4]
从网络获取的代码执行不了呢，本地的没问题

**Comment by YPLiang19** [comment]
未release之前代码中含有yacc和lex文件，需要设置Xcode的Compile Sources As 为 objective-C。现在可以直接通过pod 'MangoFix'来接入。

**Comment by YPLiang19** [comment]
未release之前代码中含有yacc和lex文件，需要设置Xcode的Compile Sources As 为 objective-C。现在可以直接通过pod 'MangoFix'来接入。
