### ISSUE TITLE
Terminating app due to uncaught exception 'MFRuntimeErrorNotFoundCFunction'

### ISSUE THREAD

**Issue by xjh093** [YPLiang19/Mango#46]
工程：MangoFixDemo
真机：iPhone X (14.2)

crash1:
*** Terminating app due to uncaught exception 'MFRuntimeErrorNotFoundCFunction', reason: 'error location line number: 223, not found CFunction: NSSearchPathForDirectoriesInDomains'

demo.mg -> line 223

crash2:
*** Terminating app due to uncaught exception 'MFRuntimeErrorNotFoundCFunction', reason: 'error location line number: 268, not found CFunction: testNativeCStringFunc'

demo.mg -> line 268

**Comment by YPLiang19** [comment]
我这边没有复现您的错误， 您可以pod update一下， 确保依赖的symdl版本在0.9.0以上， C函数的查找依赖于这个库 。

**Comment by xjh093** [comment]
解决了666，本地的还是 0.6.0
